basePath: /
host: localhost:8080
info:
  contact: {}
  description: This is a sample server for Pomodo API.
  title: Pomodo API
  version: "1.0"
paths:
  /:
    get:
      consumes:
      - '*/*'
      description: Returns a hello world message
      produces:
      - text/plain
      responses:
        "200":
          description: Hello, World!
          schema:
            type: string
      summary: Hello World endpoint
      tags:
      - hello
swagger: "2.0"
